
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: db/santex_development.sqlite3
  
test:
  <<: *default
  database: db/santex_test.sqlite3

production:
  <<: *default
  database: db/santex_production.sqlite3
